CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(25) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE tasks(
    id SERIAL PRIMARY KEY,
    description VARCHAR(200) NOT NULL,
    user_id INTEGER NOT NULL  
);

ALTER TABLE tasks ADD CONSTRAINT task_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;