services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/api
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
        - ./backend/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}